plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\User\\Documents\\cargaclik\\docs_assets"
publishOrigin = "default"
base = "C:\\Users\\User\\Documents\\cargaclik\\docs_assets"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]